services:
  windows:
    build: .
    container_name: windows
    privileged: true
    healthcheck:
      test: "[ -f /data/ready ] || exit 1"
      interval: 60s
      retries: 5
      start_period: 480s
      timeout: 2s
    environment:
      VERSION: "11"
      USERNAME: "bill"
      PASSWORD: "gates"
      DEBUG: "y"
      MANUAL: "n"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - ./scripts:/oem
      - ./shared:/data
      - ./custom.xml:/custom.xml
    networks:
      vlan:
        ipv4_address: 192.168.0.100
      vlan-1:
        ipv4_address: 192.168.1.100

networks:
  vlan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  vlan-1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24