services:
  windows-build:
    build: .
    container_name: windows-build
    privileged: true
    healthcheck:
      test: "[ -f /data/prepared ] || exit 1"
      interval: 30s
      retries: 50
      start_period: 600s
      timeout: 2s
    environment:
      VERSION: "11"
      USERNAME: "bill"
      PASSWORD: "gates"
      DISK_FMT: "qcow2"
      NETWORK: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    volumes:
      - ./scripts:/oem
      - ./custom.xml:/custom.xml
      - ./custom.iso:/custom.iso

  windows-installed:
    image: $IMAGE_NAME:$IMAGE_VERSION
    container_name: windows-installed
    privileged: true
    healthcheck:
      test: "[ -f /storage/ready ] || exit 1"
      interval: 30s
      retries: 20
      start_period: 60s
      timeout: 2s
    environment:
      VERSION: "11"
      USERNAME: "bill"
      PASSWORD: "gates"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
