services:
  windows-build:
    build: .
    container_name: windows-build
    privileged: true
    healthcheck:
      test: "[ -f /data/prepared ] || exit 1"
      interval: 30s
      retries: 50
      start_period: 600s
      timeout: 2s
    environment:
      VERSION: "11"
      USERNAME: "bill"
      PASSWORD: "gates"
      DISK_FMT: "qcow2"
      NETWORK: "Y"
      DEBUG: "Y"
      COMMIT: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m
    volumes:
      - ./windows:/storage
      - ./scripts:/oem

  windows-installed:
    image: $IMAGE_NAME:$IMAGE_VERSION
    container_name: windows-installed
    privileged: true
    healthcheck:
      test: "[ -f /local/ready ] || exit 1"
      interval: 30s
      retries: 20
      start_period: 60s
      timeout: 2s
    environment:
      VERSION: "11"
      USERNAME: "bill"
      PASSWORD: "gates"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m
