services:
  windows_2025:
    image: dockurr/windows
    container_name: windows_2025
    privileged: true
    environment:
      VERSION: "2025"
      DHCP: "Y" 
      # IP: "192.168.10.20"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    volumes:
      - ./win2025-eval.iso:/boot.iso
      - ./windows_2025_storage_task1:/storage
      - ./data_folder_2025_server:/data
    restart: always
    stop_grace_period: 2m
    networks:
      ad_vlan:
        ipv4_address: 192.168.10.201 # Fix AD(Server_2025) server IP for Docker network

  windows_11:
    image: dockurr/windows
    container_name: windows_11
    privileged: true
    environment:
      VERSION: "11"
      DHCP: "Y"
      # IP: "192.168.10.21"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    volumes:
      - ./win11x64.iso:/boot.iso
      - ./windows_11_storage_task1:/storage
      - ./data_folder_win11:/data
    stop_grace_period: 2m
    networks:
      ad_vlan:
        ipv4_address: 192.168.10.202 # Fix Windows 11 IP for Docker network
    depends_on:
      - windows_2025

networks:
  ad_vlan:
    external: true
